name 'bisscuitt-conntrackd'
version '1.0.1'
author 'Ian Bissett'
license 'Apache License 2.0'
summary 'Manages conntrackd service'
description 'Install and manages to conntrackd service to help manage stateful firewall failover'
source 'git://github.com/bisscuitt/puppet-module-conntrackd.git'
project_page 'https://github.com/bisscuitt/puppet-module-conntrackd'
dependency 'puppetlabs/stdlib', '>= 2.3.1'
